### ISSUE TITLE
Import error while running :IPython

### ISSUE THREAD

**Issue by vineet54** [wmvanvliet/vim-ipython#6]
Hello! I get the following error when I run :IPython from VIM. The error is thrown while importing the struct module. I can successfully import struct from inside ipython.

OS: Red Hat Enterprise Linux Server 7.4 
Python 3.6 from Anaconda
VIM compiled from source with python3 support

Traceback (most recent call last):                                                                                   
  File "/home/gundev1/.vim/bundle/vim-ipython/ftplugin/python/vim_ipython.py", line 145, in km_from_string           
    import IPython                                                                                                   
  File "/home/gundev1/anaconda3/lib/python3.6/site-packages/IPython/__init__.py", line 54, in <module>               
    from .core.application import Application                                                                        
  File "/home/gundev1/anaconda3/lib/python3.6/site-packages/IPython/core/application.py", line 23, in <module>       
    from traitlets.config.application import Application, catch_config_error                                         
  File "/home/gundev1/anaconda3/lib/python3.6/site-packages/traitlets/__init__.py", line 1, in <module>              
    from .traitlets import *                                                                                         
  File "/home/gundev1/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 57, in <module>            
    import six                                                                                                       
  File "/home/gundev1/anaconda3/lib/python3.6/site-packages/six.py", line 631, in <module>                           
    import struct                                                                                                    
  File "/home/gundev1/anaconda3/lib/python3.6/struct.py", line 13, in <module>                                       
    from _struct import *                                                                                            
ImportError: /home/gundev1/anaconda3/lib/python3.6/lib-dynload/_struct.cpython-36m-x86_64-linux-gnu.so: undefined sym
bol: PyDict_Size                                                                                                     
During handling of the above exception, another exception occurred:                                                  
Traceback (most recent call last):                                                                                   
  File "<string>", line 1, in <module>                                                                               
  File "/home/gundev1/.vim/bundle/vim-ipython/ftplugin/python/vim_ipython.py", line 147, in km_from_string           
    raise ImportError("Could not find IPython. " + _install_instructions)                                            
ImportError: Could not find IPython. You *must* install IPython into the Python that                                 
your vim is linked against. If you are seeing this message, this usually means                                       
either (1) installing IPython using the system Python that vim is using, or                                          
(2) recompiling Vim against the Python where you already have IPython                                                
installed. This is only a requirement to allow Vim to speak with an IPython                                          
instance using IPython's own machinery. It does *not* mean that the IPython                                          
instance with which you communicate via vim-ipython needs to be running the                                          
same version of Python.

**Comment by wmvanvliet** [comment]
First things first. The error message states:

> If you are seeing this message, this usually means
either (1) installing IPython using the system Python that vim is using, or
(2) recompiling Vim against the Python where you already have IPython
installed. This is only a requirement to allow Vim to speak with an IPython
instance using IPython's own machinery. It does not mean that the IPython
instance with which you communicate via vim-ipython needs to be running the
same version of Python.

It is common for Vim to use the system's Python (or it's own bundled version) instead of the Python installation you may be running yourself. Are you sure ipython is installed for the Python installation that your Vim is using? You can check by doing (in Vim): `py import IPython` or if you are using python3: `py3 import IPython`
